C# Fundamentals : Set1 - Task4
Mums-Who-Code/Tharani.C.Sharp pull request #4
Opened 2022-03-31 04:29 UTC by tharanisantosh

2022-04-01 20:11 UTC, ShriHumrudha requested changes

2022-04-01 20:11 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task4/Program.cs
> +namespace MyApp // Note: actual namespace depends on the project name.
Why comment?

2022-04-01 20:11 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task4/Program.cs
> +            Console.WriteLine("Muliply a and b values : " + c);
Typo

2022-04-01 20:11 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task4/Program.cs
> +
Remove extra line

2022-04-01 20:11 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task4/Program.cs
> +}
Run code cleanup

2022-04-01 20:11 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task5/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
What is this file for?

2022-04-04 11:51 UTC, tharanisantosh commented on CSharpLearning/Set1.Task4/Program.cs
> +namespace MyApp // Note: actual namespace depends on the project name.
Comment Resolved.

2022-04-04 11:51 UTC, tharanisantosh commented on CSharpLearning/Set1.Task4/Program.cs
> +            Console.WriteLine("Muliply a and b values : " + c);
Comment Resolved.

2022-04-04 11:51 UTC, tharanisantosh commented on CSharpLearning/Set1.Task4/Program.cs
> +
Removed extra line.

2022-04-04 11:52 UTC, tharanisantosh commented on CSharpLearning/Set1.Task4/Program.cs
> +}
Comment Resolved.

2022-04-04 11:52 UTC, tharanisantosh commented on CSharpLearning/Set1.Task5/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
Comment Resolved.

2022-04-05 02:12 UTC, ShriHumrudha approved these changes

2022-04-05 02:12 UTC, merged