C# Fundamentals : Set1 - Task6
Mums-Who-Code/Tharani.C.Sharp pull request #6
Opened 2022-04-14 17:34 UTC by tharanisantosh

2022-04-16 20:56 UTC, ShriHumrudha requested changes

2022-04-16 20:56 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task6/Program.cs
> +if (((player1 == player2) || (player1 == player3) || (player1 == player4) || (player1 == player5)) &&
player1 == player2 is same as player2 == player1.

2022-04-16 20:56 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task6/Program.cs
> +
Remove all the extra lines

2022-04-18 15:52 UTC, tharaniannamalai commented on CSharpLearning/Set1.Task6/Program.cs
> +if (((player1 == player2) || (player1 == player3) || (player1 == player4) || (player1 == player5)) &&
Comment Resolved.

2022-04-18 15:53 UTC, tharanisantosh commented on CSharpLearning/Set1.Task6/Program.cs
> +
Comment Resolved.

2022-04-20 04:30 UTC, ShriHumrudha requested changes

2022-04-20 04:30 UTC, ShriHumrudha commented on CSharpLearning/Set1.Task6/Program.cs
> +if (((player1 == player2) || (player1 == player3) || (player1 == player4) || (player1 == player5)) &&
In your modified code you are checking for player1 == player2 and player2 == player3 and player1 == player3. For the same logic, you are verifying it 3 times. There should be some simplified version, think about it.

2022-04-29 01:35 UTC, ShriHumrudha approved these changes

2022-04-29 01:35 UTC, merged